version: '3'

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    command: yarn serve

  server:
    build: ./server
    ports:
      - 8888:8888
    volumes:
      - ./server:/api
#    depends_on:
#      - mysql
#
#  mysql:
#    image: mysql:5.7
#    container_name: some-mysql
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=uploader
#      - MYSQL_USER=uploader
#      - MYSQL_PASSWORD=uploader
#      - MYSQL_DATABASE=uploader

